### PR TITLE
Implement Issue 13

### PR DESCRIPTION
**Pull request by drobbins**
See #13 for context.

### CODE REVIEW

**Comment by jrhorn424** [comment]
@joybuchanan Did this come from a specific request you had? Only asking for context.

**Comment by joybuchanan** [comment]
No. I'm a user. I update every day, and I noticed it's a pain. I think on the margin more people will updates if it's just two clicks.

**Comment by free-soellingeraj** [comment]
- I am getting the honeybadger error on this still.  I don't think lenny is using honeybadger in the prod app, we can ignore it.
`/Users/free-soellingeraj/code/national-fever-tracker/config/honeybadger.yml:2:in `<main>': undefined method `[]' for nil:NilClass (Honeybadger::Config::ConfigError)`

**Comment by drobbins** [comment]
@jrhorn424 It's in the smooth_user_experience Slack channel.

**Comment by free-soellingeraj** [comment]
I am merging this into master, and then deploying master.

**Pull request merged**
